/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../utils/constants';

export function TrackCross90({ isGhost, isOccupied, isSnapped, ...props }) {
  const { nodes, materials } = useGLTF('/models/track_cross90-opt.glb')

  const getMaterialColor = () => {
      if (isOccupied) return interactionColor.occupied;
      if (isSnapped) return interactionColor.snap;  
      return interactionColor.default;                 
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        name="cross90"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.cross90.geometry}
        material={nodes.cross90.material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/track_cross90-opt.glb')
