/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';

export function TrackCurved({ isGhost, isOccupied, isSnapped, isSelected, ...props }) {
  const { nodes, materials } = useGLTF('/models/track_curved-opt.glb')

  const getMaterialColor = () => {
    if (isOccupied) return interactionColor.occupied;
    if (isSnapped) return interactionColor.snap;  
    if (isSelected) return interactionColor.selected;
    return interactionColor.default;                 
  }
  
  return (
    <group {...props} dispose={null}>
      <mesh
        name="curved_track"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.track_curved.geometry}
        material={nodes.track_curved.material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/track_curved-opt.glb')
