/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';

export function TrackCurvedLeft({ isGhost, isOccupied, isSnapped, ...props }) {
  const { nodes, materials } = useGLTF('/models/track_curved_L-opt.glb')

  const getMaterialColor = () => {
    if (isOccupied) return interactionColor.occupied;
    if (isSnapped) return interactionColor.snap;  
    return interactionColor.default;                 
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        name="track_curved-l"
        castShadow
        receiveShadow
        geometry={nodes['track_curved-l'].geometry}
        material={nodes['track_curved-l'].material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/track_curved_L-opt.glb')
