/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../utils/constants';

export function TrackCurved({ isGhost, isOccupied, isSnapped, ...props }) {
  const { nodes, materials } = useGLTF('/models/track_curved-opt.glb')

  const getMaterialColor = () => {
    if (isOccupied) return interactionColor.occupied;
    if (isSnapped) return interactionColor.snap;  
    return interactionColor.default;                 
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        name="curved_track"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.curved_track.geometry}
        material={nodes.curved_track.material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/track_curved-opt.glb')
